version: "0.5"

processes:
  yarn:install:
    command: yarn install

  neos:setup:
    working_dir: neos
    # TODO Import site only if not yet imported!
    command: composer install && ./flow doctrine:migrate && ./flow site:import --package-key Zebra.Site
    depends_on:
      postgresql:createdb:
        condition: process_completed_successfully

  next:dev:
    working_dir: next
    command: yarn dev
    depends_on:
      yarn:install:
        condition: process_completed_successfully
