Networkteam:
  Neos:
    Next:
      sites:
        _default:
          nextBaseUrl: '%env:NEXT_BASE_URL%'
          revalidate:
            uri: '%env:REVALIDATE_URL%'
            token: '%env:REVALIDATE_TOKEN%'
